pool:
  vmImage: ubuntu-latest
stages:
- stage: cd
  displayName: Continuous deployment
  jobs:
  - job: docker_build_push
    displayName: Build Docker Container image
    steps:
    - task: Docker@2
      displayName: Build and push Docker container image to Azure Container Registry
      inputs:
        containerRegistry: 'azure_acr_new'
        repository: 'musicwebapp'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
    - task: Docker@2
      displayName: Push container image to Azure Container registry
      inputs:
        containerRegistry: 'azure_acr_new'
        repository: 'musicwebapp'
        command: 'push'
        tags: |
          $(Build.BuildId)
          latest
