version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    # The "app" service configuration
    # This service is built using the Dockerfile in the current directory
    # It exposes port 3000 within the container, which is mapped to port 3000 on the host machine

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    # The "nginx" service configuration
    # It uses the latest version of the nginx Docker image
    # Port 80 within the container is mapped to port 8080 on the host machine
    # The nginx.conf file in the current directory is mounted as the nginx configuration file inside the container
    # It depends on the "app" service, which means "app" will be started before "nginx"


